packages:
  - ./
  - playground/
patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true
settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict
catalog:
  "@alanscodelog/commitlint-config": ^3.1.2
  "@alanscodelog/eslint-config": ^6.3.0
  "@alanscodelog/semantic-release-config": ^6.0.0
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.1
  "@alanscodelog/vite-config": ^0.0.6
  "@commitlint/cli": ^19.8.1
  "@iconify/json": ^2.2.383
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.1.2
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.1.2
  "@nuxt/types": ^2.18.1
  "@tailwindcss/vite": ^4.1.12
  "@types/node": ^24.3.3
  "@vitejs/plugin-vue": ^6.0.1
  "@vitest/coverage-c8": ^0.33.0
  "@witchcraft/nuxt-utils": ^0.3.6
  "@witchcraft/ui": ^0.3.7
  concurrently: ^9.2.1
  cross-env: ^10.0.0
  es-toolkit: ^1.39.10
  fast-glob: ^3.3.3
  http-server: ^14.1.1
  husky: ^9.1.7
  indexit: 2.1.0-beta.3
  madge: ^8.0.0
  nuxt: ^4.2.1
  onchange: ^7.1.0
  semantic-release: ^24.2.8
  tailwindcss: ^4.1.12
  typedoc: 0.28.12
  typescript: ^5.8.3
  unplugin-icons: ^22.3.0
  unplugin-vue-components: ^29.0.0
  uuid: ^13.0.0
  vite: ^7.1.5
  vitest: ^3.2.4
  vue: ^3.5.20
  vue-tsc: ^2.2.12
  zod: ^4.1.8
