packages:
  - ./
  - playground/

allowUnusedPatches: true

catalog:
  '@alanscodelog/commitlint-config': ^3.1.2
  '@alanscodelog/eslint-config': ^6.3.1
  '@alanscodelog/semantic-release-config': ^6.0.2
  '@alanscodelog/tsconfigs': ^6.3.0
  '@alanscodelog/utils': ^6.2.0
  '@alanscodelog/vite-config': ^0.0.7
  '@commitlint/cli': ^19.8.1
  '@iconify/json': ^2.2.474
  '@nuxt/eslint-config': ^1.15.2
  '@nuxt/kit': ^4.4.6
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.4.6
  '@nuxt/types': ^2.18.1
  '@tailwindcss/vite': ^4.3.0
  '@types/node': ^24.12.4
  '@vitejs/plugin-vue': ^6.0.7
  '@vitest/coverage-v8': ^4.1.0
  '@witchcraft/nuxt-utils': ^0.3.6
  '@witchcraft/ui': ^0.5.0
  concurrently: ^9.2.1
  cross-env: ^10.1.0
  es-toolkit: ^1.46.1
  fast-glob: ^3.3.3
  http-server: ^14.1.1
  husky: ^9.1.7
  indexit: 2.1.0-beta.3
  madge: ^8.0.0
  nuxt: ^4.4.6
  onchange: ^7.1.0
  semantic-release: ^24.2.9
  tailwindcss: ^4.3.0
  typedoc: 0.28.19
  typescript: ^5.9.3
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^29.2.0
  uuid: ^13.0.2
  vite: ^7.3.3
  vitest: ^3.2.4
  vue: ^3.5.34
  vue-tsc: ^2.2.12
  zod: ^4.4.3

patchedDependencies:
  '@nuxt/module-builder': patches/@nuxt__module-builder.patch

settings:
  catalogMode: strict
  cleanupUnusedCatalogs: false
allowBuilds:
  esbuild: true
  '@alanscodelog/eslint-config': false
  '@alanscodelog/tsconfigs': false
  '@parcel/watcher': false
  core-js: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - "@alanscodelog/*"
  - "@witchcraft/*"
